### PR TITLE
Extend CSV input/output

### PR DESCRIPTION
**Pull request by EdenTewelde**
I continued working with Ralf's approach (using his csv-flie). For now I only extended the input, the output still needs to be extended.

### CODE REVIEW

**Comment by nipafx** [comment]
This PR and #51 both address #28 (although none of you included that information in your PR), which is assigned to @RalfBr. Which one do you want to work on? (This one is closer to being done but it's ok if @RalfBr wants to follow up on his solution.)

**Comment by ghost** [comment]
Choose the closer one! I`m totally fine with that.

**Comment by EdenTewelde** [comment]
@nicolaiparlog Can I merge this one too? Yesterday I already checked that this works with #52

**Comment by nipafx** [comment]
I didn't look at it yet (may have time for it in the next hour). You can of course merge "at your own risk". :wink:

**Pull request merged**
