### PR TITLE
HelloWorldTest

### LINKED ISSUE #12: JUnit
Set up JUnit 4 (by extending pom.xml) and write a Test for HelloWorld

### PR DESCRIPTION
**Pull request by EdenTewelde**
closes #12

### CODE REVIEW

**Comment by nipafx** [comment]
This PR [claims to](https://github.com/ep6-TH-Bingen/project_alpha_omega/pull/16/files) add files to the repo, which are already there. That's weird. Maybe you want to redo it? Also remember not to add `.idea` and `target` folder but the `.gitignore` should take care of that.

**Comment by EdenTewelde** [comment]
If I want to make changes do I have to close this PR and open a new one or is there another way?

**Comment by nipafx** [comment]
You could just update the branch (usually by pushing new commits) but in this case that would require some Git fiddling (rebase, conflict resolution, force pushing, ...). You may be better off just start afresh.

:bulb: You could just copy the files you edited into a temp folder, checkout master, update it to the most current upstream version, start a new branch, and then have a look at the files you wanted to edit, comparing them to the copies you made.

**Comment by nipafx** [comment]
You found a way, congrats! :smiley: I will test this later today.

**Comment by nipafx** [comment]
:+1:

**Pull request merged**
